version: '3'

services:
  # mongo:
  #   container_name: c8-mongo
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: c8
  #     MONGO_INITDB_ROOT_PASSWORD: docker

  # postgres:
  #   image: mysql
  #   container_name: c8-pg
  #   environment:
  #     - POSTGRES_DB=c8
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=docker
  #   ports:
  #     - '5432:5432'

  mysql:
    image: mysql
    container_name: c8-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: c8
      MYSQL_USER: c8
      MYSQL_PASSWORD: docker
    
  redis:
    image: redis
    container_name: c8-redis
    command: redis-server --requirepass docker
    ports:
      - '6379:6379'